/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'root': RouteRecordInfo<'root', '/', Record<never, never>, Record<never, never>>,
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'auth-otp-verify': RouteRecordInfo<'auth-otp-verify', '/auth/otp-verify', Record<never, never>, Record<never, never>>,
    'auth-phone-verify': RouteRecordInfo<'auth-phone-verify', '/auth/phone-verify', Record<never, never>, Record<never, never>>,
    'components-exness-connect': RouteRecordInfo<'components-exness-connect', '/components/exness-connect', Record<never, never>, Record<never, never>>,
    'components-forex-factory-table': RouteRecordInfo<'components-forex-factory-table', '/components/ForexFactoryTable', Record<never, never>, Record<never, never>>,
    'components-gold-exness-chart': RouteRecordInfo<'components-gold-exness-chart', '/components/GoldExnessChart', Record<never, never>, Record<never, never>>,
    'components-gold-ton-chart': RouteRecordInfo<'components-gold-ton-chart', '/components/GoldTonChart', Record<never, never>, Record<never, never>>,
    'components-gold-ton-table': RouteRecordInfo<'components-gold-ton-table', '/components/GoldTonTable', Record<never, never>, Record<never, never>>,
    'components-gold-tradingster-chart': RouteRecordInfo<'components-gold-tradingster-chart', '/components/GoldTradingsterChart', Record<never, never>, Record<never, never>>,
    'components-open-interest': RouteRecordInfo<'components-open-interest', '/components/OpenInterest', Record<never, never>, Record<never, never>>,
    'components-open-interest-split': RouteRecordInfo<'components-open-interest-split', '/components/OpenInterestSplit', Record<never, never>, Record<never, never>>,
    'dashboard': RouteRecordInfo<'dashboard', '/dashboard', Record<never, never>, Record<never, never>>,
    'gold-etf': RouteRecordInfo<'gold-etf', '/gold-etf', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'news-calendar': RouteRecordInfo<'news-calendar', '/news-calendar', Record<never, never>, Record<never, never>>,
    'open-interest': RouteRecordInfo<'open-interest', '/open-interest', Record<never, never>, Record<never, never>>,
    'second-page': RouteRecordInfo<'second-page', '/second-page', Record<never, never>, Record<never, never>>,
  }
}
